---
- name: Install package
  hosts: all
  become: true
  
  tasks:
    - name: Install user package
      yum:
        name:
          - mc
          - vim
        state: latest
      tags:
        - package

- name: Enable forwarding ipv4
  hosts:
    - inet2Router
    - inetRouter
    - centralRouter
  become: true

  tasks:
    - name: enable forwarding ipv4
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
    
    - name: restrat network
      systemd:
        name: network
        state: restarted
      tags:
        - forwarding

- name: Install nginx
  hosts: centralServer
  become: true

  tasks:
    - name: Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present

    - name: Install nginx
      yum:
        name: nginx
        state: latest
      tags:
        - package
        - nginx

    - name: Start nginx
      systemd:
        name: nginx
        state: started

    - name: Enable nginx
      systemd:
        name: nginx
        enabled: yes
